apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-setup
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: configuration
    repoURL: https://github.com/varodrig/demo-rh-tech-exchange-2023/
    targetRevision: HEAD
